name: party_games
description: "A collection of fun and interactive party games to play with friends."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  shared_preferences: ^2.5.1
  intl: ^0.20.2
  animate_do: ^3.3.4
  simple_animations: ^5.0.2
  wakelock_plus: ^1.2.11
  audioplayers: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/tasks/
    - assets/punishments/
    - assets/images/
    - assets/sounds/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
